default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: Laptop_Station_Backend_development

test:
  <<: *default
  database: Laptop_Station_Backend_test

production:
  <<: *default
  database: Laptop_Station_Backend_production
  username: Laptop_Station_Backend
  password: <%= ENV["LAPTOP_STATION_BACKEND_DATABASE_PASSWORD"] %>
